### ISSUE TITLE
VS Code Extension - Failed to activate typst-lsp

### ISSUE THREAD

**Issue by JL710** [nvarner/typst-lsp#257]
- **Component**: 
    - VSCode Extension
- **Extension version**: v0.9.4 
- **OS version and name**: Windows 10 

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

While using I get this error from vs code:
![Screenshot 2023-08-21 132643](https://github.com/nvarner/typst-lsp/assets/76447362/f5c290e2-2d6e-49ac-bf51-f181886f2c6b)

The syntax highlighting and preview is not working.

This is the error output:
```
2023-08-22 19:19:35.397 [error] Activating extension nvarner.typst-lsp failed due to an error:
2023-08-22 19:19:35.397 [error] TypeError: The argument 'file' cannot be empty. Received ''
	at new NodeError (node:internal/errors:387:5)
	at normalizeSpawnArguments (node:child_process:530:11)
	at Object.spawnSync (node:child_process:825:8)
	at Ql (c:\Users\Admin\.vscode\extensions\nvarner.typst-lsp-0.9.4-win32-x64\out\extension.js:42:55)
	at BR (c:\Users\Admin\.vscode\extensions\nvarner.typst-lsp-0.9.4-win32-x64\out\extension.js:39:61457)
	at VR (c:\Users\Admin\.vscode\extensions\nvarner.typst-lsp-0.9.4-win32-x64\out\extension.js:39:60863)
	at zR (c:\Users\Admin\.vscode\extensions\nvarner.typst-lsp-0.9.4-win32-x64\out\extension.js:39:60691)
	at Dn.eb (d:\Programme\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:13102)
	at Dn.db (d:\Programme\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:12816)
	at d:\Programme\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:10913
	at async p.n (d:\Programme\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:6206)
	at async p.m (d:\Programme\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:6169)
	at async p.l (d:\Programme\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:5626)
```

I hope I could contribute a real bug and not some mistake made by me. If you have an solution or fix I am happy to take it.

**Comment by Alessandro-Monguzzi** [comment]
Same for me. Have you resolved it?

**Comment by sagischwarz** [comment]
Version `0.9.0` was the last one working correctly for me in Ubuntu 20.04. I get the `Failed to activate typst-lsp: Error: Could not find a valid typst-lsp binary.` error starting with version `0.9.1`.

**Comment by Alessandro-Monguzzi** [comment]
I solved it by manually installing version 0.9.1 and then updating from vs code.
Before, I think I went from version 0.8.1 directly to 0.9.4

**Comment by JL710** [comment]
Installing version 9.0 or 9.1 via VS Code Extensions Panel does not fix the problem for me.

**Comment by Alessandro-Monguzzi** [comment]
Try installing via the vsix file.

**Comment by JL710** [comment]
> Try 0.9.1

Same result as before.

**Comment by nvarner** [comment]
This certainly is a bug. I can get a fix in soon.

**Comment by nvarner** [comment]
This should be fixed in the next release. Thanks for the report!
