### ISSUE TITLE
aarch64 executable cannot launch on Windows for arm

### ISSUE THREAD

**Issue by Axellwppr** [nvarner/typst-lsp#350]
- **Component**: 
    - VSCode Extension
- **Extension version**: 0.11.0
- **OS version and name**: Windows 11 Pro 23H2 ARM64

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
The precompiled aarch64 executable doesn't work on my Windows for arm laptop. If I specify `typst-lsp.serverPath` to use the x86-64 executable, it works fine (due to Arm64EC), but the efficiency suffers.

### Logs

```
2023-11-01 18:32:29.954 [error] Error: Could not find a valid typst-lsp binary.
Bundled: Failed to launch 'c:\Users\Axell\.vscode\extensions\nvarner.typst-lsp-0.11.0-win32-arm64\out\typst-lsp.exe':
	return status: 3221225595
In PATH: Failed to launch 'typst-lsp.exe':
	error: spawnSync typst-lsp.exe ENOENT
	at fR (c:\Users\Axell\.vscode\extensions\nvarner.typst-lsp-0.11.0-win32-arm64\out\extension.js:45:174)
	at lR (c:\Users\Axell\.vscode\extensions\nvarner.typst-lsp-0.11.0-win32-arm64\out\extension.js:44:47466)
	at uR (c:\Users\Axell\.vscode\extensions\nvarner.typst-lsp-0.11.0-win32-arm64\out\extension.js:44:47294)
	at q.ib (c:\Users\Axell\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:136:13192)
	at q.hb (c:\Users\Axell\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:136:12914)
	at c:\Users\Axell\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:136:11039
	at async v.n (c:\Users\Axell\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:6205)
	at async v.m (c:\Users\Axell\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:6168)
	at async v.l (c:\Users\Axell\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:5625)
```

**Comment by nvarner** [comment]
Can you run the bundled binary directly in case it gives you more debugging information?

And can you confirm if an earlier version of the plugin worked for you?

**Comment by Axellwppr** [comment]
I found this to be a problem with my system, and installing VC++ Redist 2015-2022 for arm solved it. I'm confused why windows doesn't come with it.

If anyone is experiencing the same error code below, try installing VC++ Redist.
![image](https://github.com/nvarner/typst-lsp/assets/54240325/35ad8579-465c-45e2-98c4-03b1acfcca6f)

**Comment by nvarner** [comment]
Glad you were able to fix this! Closing as resolved
