### ISSUE TITLE
Typst LSP Crash every 5 min

### ISSUE THREAD

**Issue by pragmatically-dev** [nvarner/typst-lsp#450]
- **Component**: 
    - VSCode Extension
- **Extension version: 0.12.1**: 
- **Edición	Windows 10 Home Single Language
Version	22H2
Compilación del sistema operativo	19045.4046
Windows Feature Experience Pack 1000.19053.1000.0**: 

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
The extension crash mostly when I'm writting expressions like: 
```
#set 
or
#let 
``` 

### Logs
[Info  - 1:28:39 PM] src\workspace\package\external\manager.rs:52 { message = got user external package directory; user = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }; }
[Info  - 1:28:39 PM] src\workspace\package\external\manager.rs:62 { message = got external package cache; cache = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }; }
[Info  - 1:28:39 PM] src\workspace\package\manager.rs:42 { message = initialized package manager; current = {Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/c%3A/Users/nieva/Desktop/FaMAF-SN-Notes", query: None, fragment: None }: Package { root: "file:///c%3A/Users/nieva/Desktop/FaMAF-SN-Notes" }}; external = ExternalPackageManager { providers: [LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }, LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }], cache: Some(LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }), repo: Some(RemoteRepoProvider { base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("packages.typst.org")), port: None, path: "/", query: None, fragment: None }, client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"}, timeout: 30s } }), packages: OnceCell { value: None } }; }
[Info  - 1:28:41 PM] src\server\lsp.rs:238 { message = server initialized; }
thread '<unnamed>' panicked at src\lsp_typst_boundary.rs:97:78:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src\workspace\world\typst_thread.rs:71:24:
called `Result::unwrap()` on an `Err` value: RecvError(())
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 1:28:43 PM] Connection to server got closed. Server will restart.
true
[Error - 1:28:43 PM] Server process exited with code 101.
[Info  - 1:28:44 PM] src\workspace\package\external\manager.rs:52 { message = got user external package directory; user = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }; }
[Info  - 1:28:44 PM] src\workspace\package\external\manager.rs:62 { message = got external package cache; cache = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }; }
[Info  - 1:28:44 PM] src\workspace\package\manager.rs:42 { message = initialized package manager; current = {Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/c%3A/Users/nieva/Desktop/FaMAF-SN-Notes", query: None, fragment: None }: Package { root: "file:///c%3A/Users/nieva/Desktop/FaMAF-SN-Notes" }}; external = ExternalPackageManager { providers: [LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }, LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }], cache: Some(LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }), repo: Some(RemoteRepoProvider { base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("packages.typst.org")), port: None, path: "/", query: None, fragment: None }, client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"}, timeout: 30s } }), packages: OnceCell { value: None } }; }
[Info  - 1:28:44 PM] src\server\lsp.rs:238 { message = server initialized; }
thread '<unnamed>' panicked at src\lsp_typst_boundary.rs:97:78:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src\workspace\world\typst_thread.rs:71:24:
called `Result::unwrap()` on an `Err` value: RecvError(())
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 1:28:44 PM] Connection to server got closed. Server will restart.
true
[Error - 1:28:45 PM] Server process exited with code 101.
[Info  - 1:28:45 PM] src\workspace\package\external\manager.rs:52 { message = got user external package directory; user = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }; }
[Info  - 1:28:45 PM] src\workspace\package\external\manager.rs:62 { message = got external package cache; cache = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }; }
[Info  - 1:28:45 PM] src\workspace\package\manager.rs:42 { message = initialized package manager; current = {Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/c%3A/Users/nieva/Desktop/FaMAF-SN-Notes", query: None, fragment: None }: Package { root: "file:///c%3A/Users/nieva/Desktop/FaMAF-SN-Notes" }}; external = ExternalPackageManager { providers: [LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }, LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }], cache: Some(LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }), repo: Some(RemoteRepoProvider { base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("packages.typst.org")), port: None, path: "/", query: None, fragment: None }, client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"}, timeout: 30s } }), packages: OnceCell { value: None } }; }
[Info  - 1:28:45 PM] src\server\lsp.rs:238 { message = server initialized; }
thread '<unnamed>' panicked at src\lsp_typst_boundary.rs:97:78:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src\workspace\world\typst_thread.rs:71:24:
called `Result::unwrap()` on an `Err` value: RecvError(())
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 1:28:50 PM] Connection to server got closed. Server will restart.
true
[Error - 1:28:50 PM] Server process exited with code 101.
[Info  - 1:28:51 PM] src\workspace\package\external\manager.rs:52 { message = got user external package directory; user = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }; }
[Info  - 1:28:51 PM] src\workspace\package\external\manager.rs:62 { message = got external package cache; cache = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }; }
[Info  - 1:28:51 PM] src\workspace\package\manager.rs:42 { message = initialized package manager; current = {Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/c%3A/Users/nieva/Desktop/FaMAF-SN-Notes", query: None, fragment: None }: Package { root: "file:///c%3A/Users/nieva/Desktop/FaMAF-SN-Notes" }}; external = ExternalPackageManager { providers: [LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }, LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }], cache: Some(LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }), repo: Some(RemoteRepoProvider { base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("packages.typst.org")), port: None, path: "/", query: None, fragment: None }, client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"}, timeout: 30s } }), packages: OnceCell { value: None } }; }
[Info  - 1:28:51 PM] src\server\lsp.rs:238 { message = server initialized; }
thread '<unnamed>' panicked at src\lsp_typst_boundary.rs:97:78:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src\workspace\world\typst_thread.rs:71:24:
called `Result::unwrap()` on an `Err` value: RecvError(())
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 1:28:51 PM] Connection to server got closed. Server will restart.
true
[Error - 1:28:51 PM] Server process exited with code 101.
[Info  - 1:28:51 PM] src\workspace\package\external\manager.rs:52 { message = got user external package directory; user = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }; }
[Info  - 1:28:51 PM] src\workspace\package\external\manager.rs:62 { message = got external package cache; cache = LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }; }
[Info  - 1:28:51 PM] src\workspace\package\manager.rs:42 { message = initialized package manager; current = {Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/c%3A/Users/nieva/Desktop/FaMAF-SN-Notes", query: None, fragment: None }: Package { root: "file:///c%3A/Users/nieva/Desktop/FaMAF-SN-Notes" }}; external = ExternalPackageManager { providers: [LocalProvider { root: "C:\\Users\\nieva\\AppData\\Roaming\\typst/packages/" }, LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }], cache: Some(LocalProvider { root: "C:\\Users\\nieva\\AppData\\Local\\typst/packages/" }), repo: Some(RemoteRepoProvider { base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("packages.typst.org")), port: None, path: "/", query: None, fragment: None }, client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"}, timeout: 30s } }), packages: OnceCell { value: None } }; }
[Info  - 1:28:51 PM] src\server\lsp.rs:238 { message = server initialized; }
thread '<unnamed>' panicked at src\lsp_typst_boundary.rs:101:58:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src\workspace\world\typst_thread.rs:71:24:
called `Result::unwrap()` on an `Err` value: RecvError(())
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 1:30:32 PM] The Typst Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 1:30:32 PM] Server process exited with code 101.

```
My current setup is vscode + Typst LSP extension + Typst Preview
```

**Comment by ivaquero** [comment]
Same issue on macOS

**Comment by igorlfs** [comment]
Also facing a similar issue on Linux + neovim

**Comment by truebguillaume** [comment]
I'm on macOS with typst CLI in v0.11 and typst-lsp in v0.13.0 and face the exact same issue. Has someone found anything about it? Thanks!
